os: osx
dist: trusty
language: node_js
node_js: v10
install:
- npm i
script:
- npm test
- npm run build
deploy:
  provider: npm
  email: smilingxinyi@gmail.com
  skip_cleanup: true
  api_key:
    secure: WVbL9LXCP1O4HseXs6cpkA776MU3Eoeptm1ZX15CNxARjubUcDkR2pI0MnlaeskpSpXeEUejLeikOjwRwqdN7/5v3jASRXWhypqzPnYP9x5EWXWa5QIBtNiacRTJXRxuFTT2zR+8K7q0RFlx0rasi2kUYiJliF6S26j9beKyCbg0YiRTDtsZRgZI6fqXAIZLgF/A7Zf95SEftmTI1sHqH+WMQ2nMqHEqiRCp9q7VEcfZhGcaL7acAZvx1MGHCJ61tBNputnuM/NzlzpBtlTJeHyLjXaabPWcwYVjjdey+176KZ6jTo2VuwHbqm8Zn4WEXEaZAfxq2OZJVf+lvkcOeFXOG7t3UbQ+lBnaAZwr3iEo3oa5veYSr6cDHstr7ZsYR3FV6fdzLYW8Jw69UdmMVJ0kmWydncpAl2gFUQJK52YznSIKM02Cy92g0ktOQ515+NrzVZplmBt+sYmf6pdvznEWhOj6Ur3hxTL6jqd3d2IkKi4/dL7YLqGnmTpjcP7Hsj6aXRQ+ANXvPMc8D40BykiRV/pdApFJLzVhbPtP5pvkjEakM5OlTiUPh5x34QY2qZQ2HC16E202uKyzAlbhlfJSXmg7omt833bqVNE340Dq36CwjKI8t9NICCKwiOrQVj5SfgkutrPB/4j04j8lm/aRDKlbAK66PoWmNJk9xgI=
  on:
    tags: true
    repo: misaka-ink/error-handler
