os: osx
dist: trusty
language: node_js
node_js: v10
install:
  - npm i
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: smilingxinyi@gmail.com
  skip_cleanup: true
  api_key:
    secure: KenWvBxTdozWUstY88Vw+C6t4/MQsNtkAwYDwfdTcz+rG8/dNYJCA/LkbAGgvv8vaW/HJvbX0AwOaD4Uiv8twW5f0gLQZij5aGI4HYMB7csihxUkTrvkNa4dZrN6GhppAdRSAa3xjp4+krg4c+RA1uzigtDcirWRbnfqSpRYfAoRaEtIKxJviXTO7DBf2rablBwCVuIbmG5GY9dQ1trAcv040bF2VbYbK9X7lCWlnON6bv/hdZDp5qMUHIdb2CK6IvklJZM0Fta+/xFb1W6PrEC9a5MYsdCP76lOYVUw5agbyR21g3a+4mcpAUdwAiooWMr0+aTqKIkEXEAL7wuzbkNj7EbPV2QUFIZ2YdQ/YE53XZUZljyx2VmNKcUArT3aMB6LA1Kf7kg2dHPx3FO/eQbUemu/OdYsvTHv1LtZ6ra+BiNQ/VrZ4ovVaB3EhpGLeUNVXT6o8fzTYq4FUo1KmcHFhd2u0ps1TGFtZzAmDvDksRg/V+UQHl5QVcEQhmTwhW88AzKBq3nVIpG+jbixfmFd8Y8AklMRavep1PiJ7PZYgRDjEPQIJOVi7ev7g8gdJWYNu2Wv1NVEorjbVXqRGZjPaUeU2SkNLliJa6vRmm8NPudJm/5z+FTO/RqaXIJ5Oiu1WuPWSlqiG5SDVY5UetUq1jG5YmGS7JITbYkwm+8=
  on:
    tags: true
    repo: misaka-ink/error-handler
